name: scanify
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_spinkit: ^5.2.1
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  flutter_bounce: ^1.1.0
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: 0.14.0
  flutter_native_splash: ^2.4.4


flutter_launcher_icons:
  image_path: "assets/images/app-icon.png"

  android: "launcher_icon"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app-icon.png"
  adaptive_icon_monochrome: "assets/images/app-icon.png"

  ios: true
  # image_path_ios: "assets/icon/icon.png"
  remove_alpha_channel_ios: true
  # image_path_ios_dark_transparent: "assets/icon/icon_dark.png"
  # image_path_ios_tinted_grayscale: "assets/icon/icon_tinted.png"
  # desaturate_tinted_to_grayscale_ios: true


flutter_native_splash:
  color: "#000000"  # Background color of your splash
  image: "assets/images/app-icon.png"  # App icon with transparent background
  android: true
  ios: true
  icon_background_color: "#000000"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

